### ISSUE TITLE
More Presets

### ISSUE THREAD

**Issue by DaBananaCat** [TheSquiddyLink/SplatoonRandomizer#7]
**Add more preset types:**

- [x] Alt kits
- [x] Custom brand weapons
- [x] Heavy weapons (one heavy weapon from each class, painbrush, dynamo, etc.)
- [x] Scoped chargers
- [x] Short range weapons (one short range weapon from each class, bamboozler, sploosh, etc.)
- [x] Classic weapons (one classic weapon from each class)

**Comment by TheSquiddyLink** [comment]
Added the following presets: 
Alternate Kits: 2837deb3ab88f78dddae70f632135a834aeda4e5
Custom Kits: 187d9c70b888a54e0236dfc9be5aae122daedfd4
Heavy Weapons: 92b55aadd619195f3f651fde4006b1973ac9a96e
Short Range: bd6fcb81cbd792aabd444ed90ff431ab533ba86d
Retro: 31c061651c62404b5908107397f179dcb104a72b

The retro weapons might need some adjustments

This is now pending for release in the main branch.
